version: "3"

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:${PORT}"
    networks:
      - local-omni
  
  postgres:
    image: postgres:12
    expose:
      - "5433"
    command:
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=32MB"
    environment:
      - POSTGRES_DB=omni
      - POSTGRES_USER=omni
      - POSTGRES_PASSWORD=omni
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - local-omni
  
  redis:
    image: redis
    ports:
      - "6369:6369"
    networks:
      - local-omni
  
  celery: 
    build: celery/
    command: celery -A backend worker -l info
    depends_on: 
      - redis
      - web
    volumes:
      - ./:/opt/webapp
    networks:
      - local-omni

  celery-beat:
    build: celery/
    command: celery -A backend beat -l info
    depends_on:
      - redis
      - web
    volumes:
      - ./:/opt/webapp
    networks:
      - local-omni

volumes:
  postgresql:
  redis:
  migrations:

networks:
  local-omni: